const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../assets/js/clinic-security.js'),'utf8');
const flush=()=>new Promise(r=>setImmediate(r));
async function boot({user=null,flags={},aal={currentLevel:'aal1',nextLevel:'aal1'}}={}){const nodes={},calls=[],auth=[];const el=id=>nodes[id]||(nodes[id]={hidden:true,textContent:'',disabled:false,classList:{toggle(){}},removeAttribute(){},reset(){},querySelector(){return el(id+'-button');}});const db={getUser:async()=>user,getProfile:async()=>({data:{role:'vet'}}),mfaAAL:async()=>({data:aal}),mfaList:async()=>({data:{totp:[{id:'factor',status:'verified'}]}}),onAuth:cb=>auth.push(cb),client:{auth:{resetPasswordForEmail:async(...args)=>{calls.push(args);return {};}}}};const location={href:'https://davidgavrilovic20002-spec.github.io/petfind/clinic/security.html?mode=reset',search:flags.requested?'?mode=recovery':'?mode=reset'};const ctx={document:{getElementById:el},window:{PFDB:db,PFClinicRecovery:flags},PFDB:db,URL,URLSearchParams,location,history:{replaceState(){}},setTimeout};vm.createContext(ctx);vm.runInContext(source,ctx);await flush();return {nodes,el,calls,auth,db};}
test('reset email redirects to the existing clinic, never the owner dashboard',async()=>{const h=await boot();await h.el('request-reset-form').onsubmit({preventDefault(){},target:{email:{value:'vet@example.com'},querySelector:()=>h.el('send')}});assert.equal(h.calls[0][1].redirectTo,'https://davidgavrilovic20002-spec.github.io/petfind/clinic/security.html?mode=recovery');});
test('recovery flag captured before auth initialization opens the password form',async()=>{const h=await boot({user:{email:'vet@example.com'},flags:{requested:true,credentialPresent:true}});assert.equal(h.el('set-password').hidden,false);assert.equal(h.el('request-reset').hidden,true);});
test('expired recovery link cannot open a password form using an existing session',async()=>{const h=await boot({user:{email:'vet@example.com'},flags:{requested:true,credentialPresent:true,failed:true}});assert.equal(h.el('request-reset').hidden,false);assert.equal(h.el('set-password').hidden,true);});
test('recovery with an existing authenticator requires its challenge first',async()=>{const h=await boot({user:{email:'vet@example.com'},flags:{requested:true,credentialPresent:true},aal:{currentLevel:'aal1',nextLevel:'aal2'}});assert.equal(h.el('security-settings').hidden,false);assert.equal(h.el('verify-factor-form').hidden,false);assert.equal(h.el('set-password').hidden,true);});
test('recovery initialization retains no credential strings',()=>{const ctx={location:{search:'?mode=recovery',hash:'#type=recovery&access_token=secret-value'},window:{},URLSearchParams};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/js/clinic-recovery-init.js'),'utf8'),ctx);assert.equal(ctx.window.PFClinicRecovery.credentialPresent,true);assert.doesNotMatch(JSON.stringify(ctx.window.PFClinicRecovery),/secret-value|access_token/);});
