const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/js/operations-data.js'),'utf8'),context);const api=context.PFClinicWork;
test('prescription arithmetic uses per-administration dose and concentration',()=>{const r=api.calculate('prescription_draft',{weight:10,dose:2,concentration:5,frequency:2,days:3});assert.equal(r.mg,20);assert.equal(r.ml,4);assert.equal(r.totalMl,24);assert.equal(api.calculate('prescription_draft',{weight:10,dose:2,concentration:0,frequency:2,days:3}),null);});
test('line billing rounds currency totals to cents',()=>{const r=api.calculate('billing_draft',{quantity:3,unit_price:12.34,vat:20});assert.equal(r.net,37.02);assert.equal(r.tax,7.4);assert.equal(r.total,44.42);});
test('ICU calculation converts prescribed weight-based fluid rate',()=>{assert.equal(api.calculate('icu',{weight:4,rate:2}).mlPerHour,8);assert.equal(api.calculate('icu',{weight:4,rate:''}),null);});
test('form validation rejects invalid dates and fractional repeat counts',()=>{assert.throws(()=>api.validate('intake',{title:'Intake',dob:'2026-02-30'}));assert.throws(()=>api.validate('intake',{title:'Intake',bcs:1.5}));assert.throws(()=>api.validate('icu',{title:'Care',observed_at:'2026-09-09T12:00',care:'Test',care_status:'Réalisé'}));});
test('appointment payload binds practitioner to authenticated user and rejects reversed dates',()=>{const value={title:'Consultation',starts_at:'2026-09-09T12:00',ends_at:'2026-09-09T12:30',clinic_id:'clinic',room:'Salle 1',service:'consultation',status:'scheduled',practitioner_id:'spoof'};const r=api.validate('appointment',value,'actual-vet');assert.equal(r.payload.practitioner_id,'actual-vet');assert.throws(()=>api.validate('appointment',{...value,ends_at:'2026-09-09T11:00'},'vet'));});
test('unknown fields and author spoofing are stripped from drafts',()=>{const r=api.validate('soap',{title:'Visit',subjective:'History',actor_id:'spoof',signed:true});assert.equal(r.payload.subjective,'History');assert.equal(r.payload.actor_id,undefined);assert.equal(r.payload.signed,undefined);});
test('new workflow requires actual AAL2 even without an enrolled next factor',async()=>{context.PFVet={vetIdentity:async()=>({})};context.PFDB={mfaAAL:async()=>({data:{currentLevel:'aal1',nextLevel:'aal1'}})};await assert.rejects(api.identity(),e=>e.code==='mfa_required');});
